[tool.poetry]
name = "repl_python3_beta_ninja-sword-rp"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^1.7.3"
Flask = "^2.0.2"
discord-py-slash-command = "^3.0.1"
discord-buttons = "^0.5"
discord-components = "^2.1.2"
"discord.py" = "^1.7.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
